### ISSUE TITLE
Mentions of OpenSSL in cng package

### ISSUE THREAD

**Issue by dagood** [microsoft/go-crypto-winnative#24]
I noticed these when I was doing a test run with the CNG backend in microsoft/go (and got a little confused how I'd ended up unning the OpenSSL backend on Windows 😄):

https://github.com/microsoft/go-crypto-winnative/blob/fb960ea5e37ca588133229770d7d11fc7db6b152/cng/ecdsa.go#L17-L18

And I searched for OpenSSL and saw this, too:

https://github.com/microsoft/go-crypto-winnative/blob/fb960ea5e37ca588133229770d7d11fc7db6b152/cng/rsa_test.go#L195-L196

I think the first one just needs to be updated, but with the second one I'm not sure if it's the same between OpenSSL and CNG.

**Comment by qmuntal** [comment]
Goot catch! I'll check if CNG restricts RSA key lengths when running in FIPS mode and update the comment accordingly.
