### ISSUE TITLE
Implement encoding.BinaryAppender for all CNG-backed crypto hashes

### ISSUE THREAD

**Issue by dagood** [microsoft/go-crypto-winnative#56]
I believe we need to do this here, too:

* https://github.com/golang-fips/openssl/issues/148

**Comment by qmuntal** [comment]
BCrypt doesn't support getting nor setting the hash inner state, so we can't implement `encoding.BinaryAppender`. Note that we already don't implement `encoding.BinaryMarshaller`. Our Go toolchain patches will have to deal with this.
